[custom]
; v2 QuanX 骨架：内网和中国大陆直连，其余流量使用默认节点。

ruleset=家庭内网,https://raw.githubusercontent.com/imhanjie/public/master/subconverter/ruleset/lan.list
ruleset=AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
ruleset=AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=DIRECT,https://raw.githubusercontent.com/imhanjie/public/master/subconverter/ruleset/direct.list
ruleset=DIRECT,[]GEOIP,LAN
ruleset=DIRECT,[]GEOIP,CN
ruleset=默认节点,[]FINAL

custom_proxy_group=蜂窝`select`[]DIRECT`[]电信`[]移动
custom_proxy_group=WiFi`select`[]DIRECT`.*
custom_proxy_group=HOME-SH`select`[]DIRECT`[]电信`[]移动
custom_proxy_group=HOME-AQ`select`[]DIRECT`[]电信`[]移动
custom_proxy_group=电信`select`[]DIRECT`.*
custom_proxy_group=移动`select`[]DIRECT`.*
custom_proxy_group=家庭内网`select`[]DIRECT`[]默认节点`.*
custom_proxy_group=AI`select`[]默认节点`[]DIRECT`.*
custom_proxy_group=Netflix`select`[]默认节点`[]DIRECT`.*
custom_proxy_group=TikTok`select`[]默认节点`[]DIRECT`.*

enable_rule_generator=true
overwrite_original_rules=true
