[custom]
; v2 骨架：内网和中国大陆直连，其余流量使用默认节点。

ruleset=DIRECT,[]GEOIP,LAN
ruleset=DIRECT,[]GEOIP,CN
ruleset=默认节点,[]FINAL

custom_proxy_group=默认节点`select`.*`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
